#+latex_class: cn-article
#+title: Emacs Configuration
#+author: deepwaterooo

* Updates
* starting point
- It is a new computer, and I did try to git clone from my own repository to new laptop, but after fixed errors and tried, *I promise I do NOT and can NOT bare the out-dated emacs 22.X any more, I have to move on.* I have to install newer versions for my own later on convenience. 
- Instead of configuring my own again, this time, I tried from some "big" person's repository and try to make it work on my laptop (fixing errors, installing necessary packages etc), as well as comment out some complicated modes and customize so that I would still be able to use and like my current emacs interface.
- It is the first time I tried from some big person's (or any person's configurature completely), it was tidious to fix all the errors at beginning (I spent more than 2 days on it last week. For me it just took too much time), but so far I like some of the feather's that annoying me, but I have not found good solutions to solve it, like how to auto-complete when in scripte comment line or in quotes. I like these detailed feathers which I tried by writing my own snippets from yasnippet mode before. 
- So far, org-mode is not perfect, but still like the previous verison in master branch, it is a fully functional one that I could use. 
- Will devote more time to understand email better, and to solove my own problems and make it more convenient for me to use when I want some feather. 
  
* TODOs
- org-mode src code highlight need to be fixed as soon as possible.
- some minor warnings, modes fixes needs to be done for user convenience.
- emacs key-bound for mac keyboard, so that it would be convenient for me to type some specific keys. 
- babel org-mode so I don't have to copy from specific babeled source org-mode files in order for chinese characters to work. 
- other major-modes need to be configured, for example: *java-mode*, *csharp-mode*, which I would need to use pretty soon. 
- configure and organize emacs better so that it won't take too much time responding.j

* References
- https://github.com/redguardtoo/emacs.d
